---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: header-propagator
  namespace: istio-system
spec:
  imagePullPolicy: Always
  pluginConfig:
    correlationHeader: x-request-id
    propagationHeader:
      default: lane-a
      name: x-tetrate-swimlaneid
    requestPropagation: true
    responsePropagation: true
  pluginName: header-propagator
  selector:
    matchLabels:
      header-propagation.tetrate.io/enabled: 'true'
  url: oci://docker.io/boeboe/envoy-wasm-plugins:header-propagator-0.1