---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: explore
  namespace: istio-ingress
spec:
  imagePullPolicy: Always
  phase: AUTHN
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://docker.io/boeboe/envoy-wasm-plugins:explore-0.1