---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: print-properties
  namespace: istio-ingress
spec:
  imagePullPolicy: Always
  phase: AUTHN
  pluginConfig:
    onPluginStart:
      printWasmProperties: true
      printNodeMetadataProperties: true
      printNodeProxyConfigProperties: true
      printXdsProperties: true
    onHttpRequestHeaders:
      printUpstreamProperties: true
      printRequestProperties: true
    onHttpResponseHeaders:
      printConnectionProperties: true
      printResponseProperties: true
  pluginName: print-properties
  selector:
    matchLabels:
      istio: ingress
  url: oci://docker.io/boeboe/envoy-wasm-plugins:print-properties-0.1
  vmConfig:
    env:
      - name: POD_NAME
        valueFrom: HOST
      - name: TEST_ENV_VAR
        value: testEnvValue