---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: print-properties
  namespace: istio-ingress
spec:
  imagePullPolicy: Always
  phase: AUTHN
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://docker.io/boeboe/envoy-wasm-plugins:print-properties-0.1